### PR TITLE
Vietnamese translation

### PR DESCRIPTION
**Pull request by AshleyFires**
Vietnamese translation for Krux, still need to correct some translations.

### CODE REVIEW

**Comment by jreesun** [comment]
This looks great, thank you! Let me know when this is ready for review

**Comment by jreesun** [comment]
@AshleyFires Is it ok with you if I merge this? It seems good to me! 

If any of the translations need tweaked, you could just make a new pull request later with any changes

**Comment by AshleyFires** [comment]
> @AshleyFires Is it ok with you if I merge this? It seems good to me!
> 
> If any of the translations need tweaked, you could just make a new pull request later with any changes

Yes you can! Sorry for reply a little bit late :(. I have a lot of assignment need to complete so that I can't check the comment. Sorry again!

**Comment by jreesun** [comment]
Awesome, thanks!

**Pull request merged**
